# -*- coding: utf-8 -*-
"""Rock paper scissors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swNw3McC_Bl_-KpL0PvQLQ8GHpsKpFoF
"""

import random

user = input("choose between rock, paper, and  scissors")
hi = ("rock", "paper", "scissors")
output = random.choice(hi)

te = ("it's a tie")
yo = ("you won")
ha = ("Haha u lose")

if user == output:
  print(te)
elif user == "rock" and output == "scissors":
  print(yo)
elif user == "scissors" and output == "rock":
  print(ha)
elif user == "paper" and output == "rock":
  print(yo)
elif user == "rock" and output == "paper":
  print(ha)
elif user == "scissors" and output == "paper":
  print(yo)
elif user == "paper" and output == "scissors":
  print(ha)



print(f"you chose {user} and the computer chose {output}")